### ISSUE TITLE
How to deploy this app?

### ISSUE THREAD

**Issue by ghost** [andreineculau/tastebin#15]
I would like to host it on my own server. But I don't figure out how to do it.

**Comment by andreineculau** [comment]
I'm sorry but this is so not smth to address here.
You start the the app via `npm start` and that starts an HTTP server on a port (printed in stdout, and configurable in `config.coffee`) and then you need to make that port available to the outside world (I'm not going to tell you how because there are a bunch of possible ways to do that, depending on how your server setup looks like)
